
name: Azure Web App CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies and test backend
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add any tests here

    - name: Deploy backend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<backend-app-name>'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
        package: ./app

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Build frontend React app
      working-directory: ./mychatapp
      run: |
        npm install
        npm run build

    - name: Deploy frontend to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<frontend-app-name>'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
        package: ./mychatapp/dist
